name: Check Erlang.mk

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      ## Every Monday at 4am.
      - cron: 0 4 * * 1

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        erlang:
          - '27'
        os:
#          - macos-latest
          - ubuntu-latest
          - windows-latest
        extra: ['', 'LEGACY=1']
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.erlang }}
        version-type: loose

    - name: Setup MSYS2 (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        release: false
        update: true
        install: >-
          git
          make
          diffutils

    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: make check -j 8 -k ${{ matrix.extra }}

    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      shell: msys2 {0}
      run: PATH=$INSTALL_DIR_FOR_OTP/bin:$PATH make check -j 8 -k ${{ matrix.extra }}
